+ id: Hell's Pale Ale (string, required)
+ type: ale (enum[string], required)
    + Members
        + ale
        + lager
+ style: pale (enum[string], required)
    + Members
        + amber
        + blonde
        + bock
        + dark
        + ipa
        + light
        + pale
        + pilsner
        + porter
        + stout
        + wheat
+ alcoholByVolume: 5.5 (number, required)