+ id: Tekillia (string, required)
+ type: tequila (enum[string], required)
    + Members
        + brandy
        + gin
        + rum
        + tequila
        + whiskey
        + vodka
+ alcoholByVolume: 40 (number, required)
+ proof: 80 (number, required)