+ id: Wineo Pinot (string, required)
+ type: white (enum[string], required)
    + Members
        + red
        + white
+ style: pinot (enum[string], required)
    + Members
        + cabernet
        + chardonnay
        + pinot
        + sauvignon
        + zinfandel
+ alcoholByVolume: 14 (number, required)